#!/usr/bin/env python
#coding=utf-8

import pytranslate
import getopt
import sys
from AppKit import NSPasteboard, NSArray

opts, params = getopt.getopt(sys.argv[1:], 'r:p')

sl = 'english'
tl = 'czech'
paste = False

for o,p in opts:
    if o in ['-p']:
        print "Paste Enabled \n"
        paste = True
    if o in ['-r']:
        sl = 'czech'
        tl = 'english'
        
if len(params) > 0:
    t_string = params[0]
else:
    t_string = opts[-1:][0][1]
    print t_string
    
res = pytranslate.translate(t_string, sl=sl, tl=tl)

if paste:
    ps = NSPasteboard.generalPasteboard()
    ps.clearContents()
    a = NSArray.arrayWithObject_(unicode(res))
    ps.writeObjects_(a)
    
print res
