#!/usr/bin/env python
#coding=utf-8

import pytranslate
import getopt
import sys
from AppKit import NSPasteboard, NSArray

opts, params = getopt.getopt(sys.argv[1:], 'r:np')

sl = 'english'
tl = 'czech'
paste = True

for o,p in opts:
    if o in ['-np']:
        paste = False
    if o in ['-r']:
        sl = 'czech'
        tl = 'english'
res = pytranslate.translate(params[0], sl=sl, tl=tl)

if paste:
    ps = NSPasteboard.generalPasteboard()
    ps.clearContents()
    a = NSArray.arrayWithObject_(unicode(res))
    ps.writeObjects_(a)
print res
